import { AssetInfo } from '@defidojo/shared-types';

/**
 * Transforms Snowflake's UPPERCASE response format to camelCase AssetInfo
 * @param snowflakeData Raw data from Snowflake DB in UPPERCASE
 */
export function transformSnowflakeToApi(snowflakeData: any): AssetInfo {
    return {
        id: snowflakeData?.ID || '',
        symbol: (snowflakeData?.SYMBOL || '').toLowerCase(),
        name: snowflakeData?.NAME || '',
        webSlug: snowflakeData.WEB_SLUG,
        assetPlatformId: snowflakeData.ASSET_PLATFORM_ID,
        platforms: snowflakeData.PLATFORMS,
        detailPlatforms: snowflakeData.DETAIL_PLATFORMS,
        blockTimeInMinutes: snowflakeData.BLOCK_TIME_IN_MINUTES,
        hashingAlgorithm: snowflakeData.HASHING_ALGORITHM,
        categories: snowflakeData.CATEGORIES,
        previewListing: snowflakeData.PREVIEW_LISTING,
        publicNotice: snowflakeData.PUBLIC_NOTICE,
        additionalNotices: snowflakeData.ADDITIONAL_NOTICES,
        localization: snowflakeData.LOCALIZATION,
        description: snowflakeData.DESCRIPTION,
        links: {
            homepage: snowflakeData.LINKS?.HOMEPAGE,
            whitepaper: snowflakeData.LINKS?.WHITEPAPER,
            blockchainSite: snowflakeData.LINKS?.BLOCKCHAIN_SITE,
            officialForumUrl: snowflakeData.LINKS?.OFFICIAL_FORUM_URL,
            chatUrl: snowflakeData.LINKS?.CHAT_URL,
            announcementUrl: snowflakeData.LINKS?.ANNOUNCEMENT_URL,
            snapshotUrl: snowflakeData.LINKS?.SNAPSHOT_URL,
            twitterScreenName: snowflakeData.LINKS?.TWITTER_SCREEN_NAME,
            facebookUsername: snowflakeData.LINKS?.FACEBOOK_USERNAME,
            bitcointalkThreadIdentifier: snowflakeData.LINKS?.BITCOINTALK_THREAD_IDENTIFIER,
            telegramChannelIdentifier: snowflakeData.LINKS?.TELEGRAM_CHANNEL_IDENTIFIER,
            subredditUrl: snowflakeData.LINKS?.SUBREDDIT_URL,
            reposUrl: {
                github: snowflakeData.LINKS?.REPOS_URL?.GITHUB || [],
                bitbucket: snowflakeData.LINKS?.REPOS_URL?.BITBUCKET || []
            }
        },
        image: {
            thumb: snowflakeData.IMAGE?.THUMB,
            small: snowflakeData.IMAGE?.SMALL,
            large: snowflakeData.IMAGE?.LARGE
        },
        marketData: {
            currentPrice: snowflakeData.MARKET_DATA?.CURRENT_PRICE || {},
            totalValueLocked: snowflakeData.MARKET_DATA?.TOTAL_VALUE_LOCKED || null,
            mcapToTvlRatio: snowflakeData.MARKET_DATA?.MCAP_TO_TVL_RATIO || null,
            fdvToTvlRatio: snowflakeData.MARKET_DATA?.FDV_TO_TVL_RATIO || null,
            roi: snowflakeData.MARKET_DATA?.ROI || null,
            ath: snowflakeData.MARKET_DATA?.ATH || {},
            athChangePercentage: snowflakeData.MARKET_DATA?.ATH_CHANGE_PERCENTAGE || {},
            athDate: snowflakeData.MARKET_DATA?.ATH_DATE || {},
            atl: snowflakeData.MARKET_DATA?.ATL || {},
            atlChangePercentage: snowflakeData.MARKET_DATA?.ATL_CHANGE_PERCENTAGE || {},
            atlDate: snowflakeData.MARKET_DATA?.ATL_DATE || {},
            marketCap: snowflakeData.MARKET_DATA?.MARKET_CAP || {},
            marketCapRank: snowflakeData.MARKET_DATA?.MARKET_CAP_RANK || null,
            fullyDilutedValuation: snowflakeData.MARKET_DATA?.FULLY_DILUTED_VALUATION || {},
            totalVolume: snowflakeData.MARKET_DATA?.TOTAL_VOLUME || {},
            high24h: snowflakeData.MARKET_DATA?.HIGH_24H || {},
            low24h: snowflakeData.MARKET_DATA?.LOW_24H || {},
            priceChange24h: snowflakeData.MARKET_DATA?.PRICE_CHANGE_24H || null,
            priceChangePercentage24h: snowflakeData.MARKET_DATA?.PRICE_CHANGE_PERCENTAGE_24H || null,
            priceChangePercentage7d: snowflakeData.MARKET_DATA?.PRICE_CHANGE_PERCENTAGE_7D || null,
            priceChangePercentage14d: snowflakeData.MARKET_DATA?.PRICE_CHANGE_PERCENTAGE_14D || null,
            priceChangePercentage30d: snowflakeData.MARKET_DATA?.PRICE_CHANGE_PERCENTAGE_30D || null,
            priceChangePercentage60d: snowflakeData.MARKET_DATA?.PRICE_CHANGE_PERCENTAGE_60D || null,
            priceChangePercentage200d: snowflakeData.MARKET_DATA?.PRICE_CHANGE_PERCENTAGE_200D || null,
            priceChangePercentage1y: snowflakeData.MARKET_DATA?.PRICE_CHANGE_PERCENTAGE_1Y || null,
            marketCapChange24h: snowflakeData.MARKET_DATA?.MARKET_CAP_CHANGE_24H || null,
            marketCapChangePercentage24h: snowflakeData.MARKET_DATA?.MARKET_CAP_CHANGE_PERCENTAGE_24H || null,
            priceChange24hInCurrency: snowflakeData.MARKET_DATA?.PRICE_CHANGE_24H_IN_CURRENCY || {},
            priceChangePercentage1hInCurrency: snowflakeData.MARKET_DATA?.PRICE_CHANGE_PERCENTAGE_1H_IN_CURRENCY || {},
            priceChangePercentage24hInCurrency: snowflakeData.MARKET_DATA?.PRICE_CHANGE_PERCENTAGE_24H_IN_CURRENCY || {},
            priceChangePercentage7dInCurrency: snowflakeData.MARKET_DATA?.PRICE_CHANGE_PERCENTAGE_7D_IN_CURRENCY || {},
            priceChangePercentage14dInCurrency: snowflakeData.MARKET_DATA?.PRICE_CHANGE_PERCENTAGE_14D_IN_CURRENCY || {},
            priceChangePercentage30dInCurrency: snowflakeData.MARKET_DATA?.PRICE_CHANGE_PERCENTAGE_30D_IN_CURRENCY || {},
            priceChangePercentage60dInCurrency: snowflakeData.MARKET_DATA?.PRICE_CHANGE_PERCENTAGE_60D_IN_CURRENCY || {},
            priceChangePercentage200dInCurrency: snowflakeData.MARKET_DATA?.PRICE_CHANGE_PERCENTAGE_200D_IN_CURRENCY || {},
            priceChangePercentage1yInCurrency: snowflakeData.MARKET_DATA?.PRICE_CHANGE_PERCENTAGE_1Y_IN_CURRENCY || {},
            marketCapChange24hInCurrency: snowflakeData.MARKET_DATA?.MARKET_CAP_CHANGE_24H_IN_CURRENCY || {},
            marketCapChangePercentage24hInCurrency: snowflakeData.MARKET_DATA?.MARKET_CAP_CHANGE_PERCENTAGE_24H_IN_CURRENCY || {},
            totalSupply: snowflakeData.MARKET_DATA?.TOTAL_SUPPLY || null,
            maxSupply: snowflakeData.MARKET_DATA?.MAX_SUPPLY || null,
            circulatingSupply: snowflakeData.MARKET_DATA?.CIRCULATING_SUPPLY || null,
            lastUpdated: snowflakeData.MARKET_DATA?.LAST_UPDATED || null,
            marketCapFdvRatio: snowflakeData.MARKET_DATA?.MARKET_CAP_FDV_RATIO || null
        },
        communityData: {
            facebookLikes: snowflakeData.COMMUNITY_DATA?.FACEBOOK_LIKES,
            twitterFollowers: snowflakeData.COMMUNITY_DATA?.TWITTER_FOLLOWERS,
            redditAveragePosts48h: snowflakeData.COMMUNITY_DATA?.REDDIT_AVERAGE_POSTS_48H,
            redditAverageComments48h: snowflakeData.COMMUNITY_DATA?.REDDIT_AVERAGE_COMMENTS_48H,
            redditSubscribers: snowflakeData.COMMUNITY_DATA?.REDDIT_SUBSCRIBERS,
            redditAccountsActive48h: snowflakeData.COMMUNITY_DATA?.REDDIT_ACCOUNTS_ACTIVE_48H,
            telegramChannelUserCount: snowflakeData.COMMUNITY_DATA?.TELEGRAM_CHANNEL_USER_COUNT
        },
        developerData: {
            forks: snowflakeData.DEVELOPER_DATA?.FORKS,
            stars: snowflakeData.DEVELOPER_DATA?.STARS,
            subscribers: snowflakeData.DEVELOPER_DATA?.SUBSCRIBERS,
            totalIssues: snowflakeData.DEVELOPER_DATA?.TOTAL_ISSUES,
            closedIssues: snowflakeData.DEVELOPER_DATA?.CLOSED_ISSUES,
            pullRequestsMerged: snowflakeData.DEVELOPER_DATA?.PULL_REQUESTS_MERGED,
            pullRequestContributors: snowflakeData.DEVELOPER_DATA?.PULL_REQUEST_CONTRIBUTORS,
            codeAdditionsDeletions4Weeks: snowflakeData.DEVELOPER_DATA?.CODE_ADDITIONS_DELETIONS_4_WEEKS,
            commitCount4Weeks: snowflakeData.DEVELOPER_DATA?.COMMIT_COUNT_4_WEEKS,
            last4WeeksCommitActivitySeries: snowflakeData.DEVELOPER_DATA?.LAST_4_WEEKS_COMMIT_ACTIVITY_SERIES
        },
        statusUpdates: snowflakeData.STATUS_UPDATES,
        lastUpdated: snowflakeData.LAST_UPDATED,
        tickers: snowflakeData.TICKERS,
        pythPriceFeedId: snowflakeData.PYTH_PRICE_FEED_ID,
        coingeckoId: snowflakeData.COINGECKO_ID,
        isActive: snowflakeData.IS_ACTIVE,
        countryOrigin: snowflakeData.COUNTRY_ORIGIN,
        genesisDate: snowflakeData.GENESIS_DATE,
        sentimentVotesUpPercentage: snowflakeData.SENTIMENT_VOTES_UP_PERCENTAGE,
        sentimentVotesDownPercentage: snowflakeData.SENTIMENT_VOTES_DOWN_PERCENTAGE
    };
}

/**
 * Transforms CoinGecko's snake_case response format to camelCase AssetInfo
 * @param coinGeckoData Raw data from CoinGecko API in snake_case
 */
export function transformCoinGeckoToApi(coinGeckoData: any): AssetInfo {
    return {
        id: coinGeckoData.id,
        symbol: coinGeckoData.symbol,
        name: coinGeckoData.name,
        webSlug: coinGeckoData.id,
        assetPlatformId: coinGeckoData.asset_platform_id,
        platforms: coinGeckoData.platforms,
        detailPlatforms: coinGeckoData.detail_platforms,
        blockTimeInMinutes: coinGeckoData.block_time_in_minutes,
        hashingAlgorithm: coinGeckoData.hashing_algorithm,
        categories: coinGeckoData.categories,
        previewListing: coinGeckoData.preview_listing,
        publicNotice: coinGeckoData.public_notice,
        additionalNotices: coinGeckoData.additional_notices,
        localization: coinGeckoData.localization,
        description: coinGeckoData.description,
        links: {
            homepage: coinGeckoData.links?.homepage,
            whitepaper: coinGeckoData.links?.whitepaper,
            blockchainSite: coinGeckoData.links?.blockchain_site,
            officialForumUrl: coinGeckoData.links?.official_forum_url,
            chatUrl: coinGeckoData.links?.chat_url,
            announcementUrl: coinGeckoData.links?.announcement_url,
            snapshotUrl: coinGeckoData.links?.snapshot_url,
            twitterScreenName: coinGeckoData.links?.twitter_screen_name,
            facebookUsername: coinGeckoData.links?.facebook_username,
            bitcointalkThreadIdentifier: coinGeckoData.links?.bitcointalk_thread_identifier,
            telegramChannelIdentifier: coinGeckoData.links?.telegram_channel_identifier,
            subredditUrl: coinGeckoData.links?.subreddit_url,
            reposUrl: {
                github: coinGeckoData.links?.repos_url?.github || [],
                bitbucket: coinGeckoData.links?.repos_url?.bitbucket || []
            }
        },
        image: {
            thumb: coinGeckoData.image?.thumb,
            small: coinGeckoData.image?.small,
            large: coinGeckoData.image?.large
        },
        marketData: {
            currentPrice: coinGeckoData.market_data?.current_price || {},
            totalValueLocked: coinGeckoData.market_data?.total_value_locked || null,
            mcapToTvlRatio: coinGeckoData.market_data?.mcap_to_tvl_ratio || null,
            fdvToTvlRatio: coinGeckoData.market_data?.fdv_to_tvl_ratio || null,
            roi: coinGeckoData.market_data?.roi || null,
            ath: coinGeckoData.market_data?.ath || {},
            athChangePercentage: coinGeckoData.market_data?.ath_change_percentage || {},
            athDate: coinGeckoData.market_data?.ath_date || {},
            atl: coinGeckoData.market_data?.atl || {},
            atlChangePercentage: coinGeckoData.market_data?.atl_change_percentage || {},
            atlDate: coinGeckoData.market_data?.atl_date || {},
            marketCap: coinGeckoData.market_data?.market_cap || {},
            marketCapRank: coinGeckoData.market_data?.market_cap_rank || null,
            fullyDilutedValuation: coinGeckoData.market_data?.fully_diluted_valuation || {},
            totalVolume: coinGeckoData.market_data?.total_volume || {},
            high24h: coinGeckoData.market_data?.high_24h || {},
            low24h: coinGeckoData.market_data?.low_24h || {},
            priceChange24h: coinGeckoData.market_data?.price_change_24h || null,
            priceChangePercentage24h: coinGeckoData.market_data?.price_change_percentage_24h || null,
            priceChangePercentage7d: coinGeckoData.market_data?.price_change_percentage_7d || null,
            priceChangePercentage14d: coinGeckoData.market_data?.price_change_percentage_14d || null,
            priceChangePercentage30d: coinGeckoData.market_data?.price_change_percentage_30d || null,
            priceChangePercentage60d: coinGeckoData.market_data?.price_change_percentage_60d || null,
            priceChangePercentage200d: coinGeckoData.market_data?.price_change_percentage_200d || null,
            priceChangePercentage1y: coinGeckoData.market_data?.price_change_percentage_1y || null,
            marketCapChange24h: coinGeckoData.market_data?.market_cap_change_24h || null,
            marketCapChangePercentage24h: coinGeckoData.market_data?.market_cap_change_percentage_24h || null,
            priceChange24hInCurrency: coinGeckoData.market_data?.price_change_24h_in_currency || {},
            priceChangePercentage1hInCurrency: coinGeckoData.market_data?.price_change_percentage_1h_in_currency || {},
            priceChangePercentage24hInCurrency: coinGeckoData.market_data?.price_change_percentage_24h_in_currency || {},
            priceChangePercentage7dInCurrency: coinGeckoData.market_data?.price_change_percentage_7d_in_currency || {},
            priceChangePercentage14dInCurrency: coinGeckoData.market_data?.price_change_percentage_14d_in_currency || {},
            priceChangePercentage30dInCurrency: coinGeckoData.market_data?.price_change_percentage_30d_in_currency || {},
            priceChangePercentage60dInCurrency: coinGeckoData.market_data?.price_change_percentage_60d_in_currency || {},
            priceChangePercentage200dInCurrency: coinGeckoData.market_data?.price_change_percentage_200d_in_currency || {},
            priceChangePercentage1yInCurrency: coinGeckoData.market_data?.price_change_percentage_1y_in_currency || {},
            marketCapChange24hInCurrency: coinGeckoData.market_data?.market_cap_change_24h_in_currency || {},
            marketCapChangePercentage24hInCurrency: coinGeckoData.market_data?.market_cap_change_percentage_24h_in_currency || {},
            totalSupply: coinGeckoData.market_data?.total_supply || null,
            maxSupply: coinGeckoData.market_data?.max_supply || null,
            circulatingSupply: coinGeckoData.market_data?.circulating_supply || null,
            lastUpdated: coinGeckoData.market_data?.last_updated || null,
            marketCapFdvRatio: coinGeckoData.market_data?.market_cap_fdv_ratio || null
        },
        communityData: {
            facebookLikes: coinGeckoData.community_data?.facebook_likes,
            twitterFollowers: coinGeckoData.community_data?.twitter_followers,
            redditAveragePosts48h: coinGeckoData.community_data?.reddit_average_posts_48h,
            redditAverageComments48h: coinGeckoData.community_data?.reddit_average_comments_48h,
            redditSubscribers: coinGeckoData.community_data?.reddit_subscribers,
            redditAccountsActive48h: coinGeckoData.community_data?.reddit_accounts_active_48h,
            telegramChannelUserCount: coinGeckoData.community_data?.telegram_channel_user_count
        },
        developerData: {
            forks: coinGeckoData.developer_data?.forks,
            stars: coinGeckoData.developer_data?.stars,
            subscribers: coinGeckoData.developer_data?.subscribers,
            totalIssues: coinGeckoData.developer_data?.total_issues,
            closedIssues: coinGeckoData.developer_data?.closed_issues,
            pullRequestsMerged: coinGeckoData.developer_data?.pull_requests_merged,
            pullRequestContributors: coinGeckoData.developer_data?.pull_request_contributors,
            codeAdditionsDeletions4Weeks: coinGeckoData.developer_data?.code_additions_deletions_4_weeks,
            commitCount4Weeks: coinGeckoData.developer_data?.commit_count_4_weeks,
            last4WeeksCommitActivitySeries: coinGeckoData.developer_data?.last_4_weeks_commit_activity_series
        },
        statusUpdates: coinGeckoData.status_updates,
        lastUpdated: coinGeckoData.last_updated,
        tickers: coinGeckoData.tickers,
        pythPriceFeedId: coinGeckoData.pyth_price_feed_id,
        coingeckoId: coinGeckoData.id,
        isActive: coinGeckoData.is_active,
        countryOrigin: coinGeckoData.country_origin,
        genesisDate: coinGeckoData.genesis_date,
        sentimentVotesUpPercentage: coinGeckoData.sentiment_votes_up_percentage,
        sentimentVotesDownPercentage: coinGeckoData.sentiment_votes_down_percentage
    };
}
