name: Deploy to Vercel
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Frontend Deployment
      - name: Deploy Frontend
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_FRONTEND }}
        run: |
          cd $GITHUB_WORKSPACE/frontend
          npm install
          npm install --global vercel@latest
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }} --cwd $GITHUB_WORKSPACE/frontend
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }} --cwd $GITHUB_WORKSPACE/frontend
          vercel deploy --prebuilt --prod --yes --token=${{ secrets.VERCEL_TOKEN }} --cwd $GITHUB_WORKSPACE/frontend

      # Backend Deployment
      - name: Deploy Backend
        working-directory: ./backend
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_BACKEND }}
        run: |
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --prod --yes --token=${{ secrets.VERCEL_TOKEN }}